name: Manual
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        description: 'Log level'
        required: true
        default: 'info'
        options:
          info:
            description: 'Info'
          warning:
            description: 'Warning'
          error:
            description: 'Error'
          debug:
            description: 'Debug'
          critical:
            description: 'Critical'
          alert:
            description: 'Alert'
          emergency:
            description: 'Emergency'
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!
      - uses: actions/checkout@v4
   