name: Contexts
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github.actor }}"
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.event }}"
      - run: echo "${{ github.repository }}"
      - run: echo "${{ github.workspace }}"
   