name: Contexts
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      PASS: ${{ secrets.PASS }}
    steps:
      - run: echo "${{ github.actor }}"
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.event.pull_request.title }}"
      - run: echo "${{ github.repository }}"
      - run: echo "${{ runner.os }} ${{ runner.os_version }}"
      - run: echo "${{ runner.arch }}"
      - run: echo "${{ runner.debug }}"
      - run: echo "${GITHUB_API_URL}"
      - run: echo "${{ vars.USERNAME }}"
      - run: echo "${PASS}"
      - run: echo "${PASS:0:1} ${PASS#?}"
   