name: Conditions
on: push
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
        if: ${{ contains(github.run_id, '1') }}
      - run: exit 1
      - run: echo "World"
        if ${{ failure() }} 