name: Manual
on:
  workflow_dispatch:
    inputs:
      log-level:
        type: choice
        description: 'Log level'
        required: true
        default: 'info'
        options:
          - info
          - warning
          - error
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!
      - uses: actions/checkout@v4
   