name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        description: 'Person to greet'
        required: true
        default: 'Hello'
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, world!
      - uses: actions/checkout@v4
   